### ISSUE TITLE
Is Nello  still working?

### ISSUE THREAD

**Issue by My1GH** [pschmitt/contact#1]
I saw you recently updated files.

**Comment by pschmitt** [comment]
Haven't had this thing working in years. The changes you saw were just dependencies updates (dependabot).
AFAIK nello is dead.

**Comment by zaptrem** [comment]
What did you replace your Nello unit with? I was hoping I could MITM their internal API to continue using the device but haven't found any documentation online.

**Comment by pschmitt** [comment]
MITM is the way to go. This is exactly what I did to implement pynello.

Here's what I replaced my nello with: https://nuki.io/en/opener/
