### ISSUE TITLE
[pyrundeck] I volunteer to maintain this package

### ISSUE THREAD

**Issue by xavier8854** [pschmitt/contact#2]
Hi @pschmitt 
If you agree, I volunteer to maintain pyrundeck package
Regards,

Xavier

**Comment by pschmitt** [comment]
Salut, Xavier.
Imma add you to pyrundeck.

**Comment by pschmitt** [comment]
Invite is out.

**Comment by emersonyh** [comment]
If you want some extra help, I also would like to help, also have one PR waiting, and if that's approved I'll send more

**Comment by pschmitt** [comment]
![image](https://github.com/user-attachments/assets/946ba28a-cfa6-46f5-9350-325d0814f4d6)

**Comment by emersonyh** [comment]
Thanks!

**Comment by emersonyh** [comment]
Can we get a Telegram channel, Discord, Slack or something between us just to agreed before we do new releases, PRs, etc?

**Comment by pschmitt** [comment]
Feel free to set something up.
I don't want to be involved all too much in that.
